version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation_backend
    ports:
      - "8000:8000"
    volumes:
      - ./exports:/app/exports
      - ./temp:/app/temp
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
